//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRKit.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Details
    {
        public int Id { get; set; }
        public int TranId { get; set; }
        public decimal Cost { get; set; }
        public int Order { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
