//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRKit.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Initial { get; set; }
        public int TranCount { get; set; }
        public decimal Step { get; set; }
    
        public virtual Transaction_Details Transaction_Details { get; set; }
    }
}
