//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRKit.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VRKitEntities : DbContext
    {
        public VRKitEntities()
            : base("name=VRKitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Transaction_Details> Transaction_Details { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    
        public virtual int Alter_Lookup(string key, Nullable<decimal> numValue)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            var numValueParameter = numValue.HasValue ?
                new ObjectParameter("NumValue", numValue) :
                new ObjectParameter("NumValue", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Alter_Lookup", keyParameter, numValueParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Create_Transaction(Nullable<int> initial, Nullable<int> trancount, Nullable<int> step)
        {
            var initialParameter = initial.HasValue ?
                new ObjectParameter("Initial", initial) :
                new ObjectParameter("Initial", typeof(int));
    
            var trancountParameter = trancount.HasValue ?
                new ObjectParameter("Trancount", trancount) :
                new ObjectParameter("Trancount", typeof(int));
    
            var stepParameter = step.HasValue ?
                new ObjectParameter("Step", step) :
                new ObjectParameter("Step", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Create_Transaction", initialParameter, trancountParameter, stepParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Create_Transaction_Details(Nullable<int> tranID, Nullable<decimal> cost, Nullable<decimal> order)
        {
            var tranIDParameter = tranID.HasValue ?
                new ObjectParameter("TranID", tranID) :
                new ObjectParameter("TranID", typeof(int));
    
            var costParameter = cost.HasValue ?
                new ObjectParameter("Cost", cost) :
                new ObjectParameter("Cost", typeof(decimal));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Create_Transaction_Details", tranIDParameter, costParameter, orderParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Read_Lookup(string key, string type)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Read_Lookup", keyParameter, typeParameter);
        }
    
        public virtual ObjectResult<Read_Lookup_Defaults_Result> Read_Lookup_Defaults()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Read_Lookup_Defaults_Result>("Read_Lookup_Defaults");
        }
    
        public virtual ObjectResult<Read_Transaction_Groups_Result> Read_Transaction_Groups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Read_Transaction_Groups_Result>("Read_Transaction_Groups");
        }
    
        public virtual ObjectResult<Read_Transactions_Result> Read_Transactions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Read_Transactions_Result>("Read_Transactions");
        }
    }
}
